security:
    encoders:
      App\Entity\User:
        algorithm: auto

    providers:
      app_user_provider:
        entity:
          class: App\Entity\User
          property: email

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      main:
        anonymous: true
        lazy: true
        provider: app_user_provider
        guard:
          authenticators:
            - App\Security\MNAuthenticator
        logout:
          path: app_logout
          # where to redirect after logout
          # target: app_any_route

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    access_control:
      - { path: '^/admin', roles: ROLE_ADMIN }
      